Add encrpytion, snapshot retention management.
* Added encryption support (-w, -I) for backup sets.
* Snapshots are now auto-managed on successful sync, based on retention
  policy set.
* Removed non-recursive support. Any dataset (recursive or not) with recursive
  set enables remote snapshot management.
* Standardized variable usage.

diff --git a/zincrsend b/zincrsend
--- a/zincrsend
+++ b/zincrsend
@@ -1,156 +1,143 @@
 #!/usr/bin/env bash
 #
-# Incremental ZFS send/recv backup script
+# Incremental ZFS send/recv backup, encryption support, snapshot management.
+# Original: https://github.com/bahamas10/zincrsend
 #
-# Author: Dave Eddy <dave@daveeddy.com>
-# Date: November 20, 2015
-# License: MIT
+# Exit codes:
+#   0: success.
+#   1: local snapshot creation failed.
+#   2: latest remote snapshot does not exist locally (manual intervention
+#      required).
+#   3: ZFS send/recv failed.
 
-#########
-# config
-#########
-
-# datasets to send
+################################################################################
+# Configuration options
+################################################################################
+# Recursive datasets to send. (-R) will remove snapshots that have been deleted
+# locally on the remote end as well. Dataset do *NOT* need to have children. 
 datasets=(
-)
-# datasets to send recursively
-# even if a dataset does not have any descendant datasets, using a
-# recursive zfs send (-R) is preferable because it will result
-# in locally removed snapshots being removed on the remote end as well
-datasets_recursive=(
-	goliath/public
-	goliath/minecraft
-	goliath/backups
+  tank/example_dataset
 )
 
-# information about the server on the receiving end
-remote_server='my-backup-server.example.com'
-remote_user='dave'
+# Remote server connection settings.
+remote_server='192.168.0.10'
+remote_user='zfs_snapshot'
 remote_port='22'
-remote_dataset='paper' # zpool name most likely
-remote_command_prefix='sudo' # leave blank for nothing
-remote_ssh_opts=(-i /root/backup/backup.key) # additional opts to give to ssh
+remote_pool='backup'
+remote_command_prefix='sudo'
+remote_ssh_opts=(-i /etc/zfs_snapshot/.ssh/id_rsa)
 
 # prefix to use for snapshots created by this script
-snapshot_prefix='zincrsend_'
-
-# higher = more output
-verbosity_level=0
-
-# function to execute at the end - can be anything
-# $1 - exit code - the code that will be used when this script exits
-# returns - nothing
-end() {
-	local exitcode=$1
-	local msg=
-	case "$exitcode" in
-		0) msg='ok';;
-		*) msg='failed';;
-	esac
-	/opt/custom/bin/pushover zincrsend "$msg - took $((SECONDS / 60)) minutes"
-}
-
-#############
-# end config
-#############
-
-debug() {
-	((verbosity_level >= 1)) && echo "[DEBUG] $*" >&2
-	return 0
-}
-trace() {
-	((verbosity_level >= 2)) && echo "[TRACE] $*" >&2
-	return 0
-}
+snapshot_prefix=''
+# Number of snapshots to retain after successful sync. 0 disables.
+# If running as a non-root user, be sure to add user with mount,destroy privileges
+# on the dataset. This will allow snapshot management.
+#
+#  /usr/sbin/zfs allow -d {ZFS USER} mount,destroy tank/example_dataset
+#
+snapshot_retention=1
+# snapshot options: https://openzfs.github.io/openzfs-docs/man/8/zfs-snapshot.8.html
+snapshot_opts=(-r)
+# send options: https://openzfs.github.io/openzfs-docs/man/8/zfs-send.8.html
+send_opts=(-R -w)
+################################################################################
 
 SSH() {
-	trace "ssh ${remote_ssh_opts[*]} $remote_server $remote_command_prefix $*"
-	ssh \
-		"${remote_ssh_opts[@]}" \
-		-l "$remote_user" \
-		-p "$remote_port" \
-		"$remote_server" \
-		"$remote_command_prefix" \
-		"$@"
+  echo "ssh ${remote_ssh_opts[*]} ${remote_server} ${remote_command_prefix} $*"
+  ssh \
+    "${remote_ssh_opts[@]}" \
+    -l "${remote_user}" \
+    -p "${remote_port}" \
+    "${remote_server}" \
+    "${remote_command_prefix}" \
+    "${@}"
 }
 
 process() {
-	local ds=$1
+  local ds=${1}
 
-	local snapshot_opts=()
-	local send_opts=()
-	if [[ -n $2 ]]; then
-		# recursive
-		snapshot_opts+=(-r)
-		send_opts+=(-R)
-	fi
+  echo ''
+  echo "processing dataset: ${ds}"
+  echo ''
 
-	echo ''
-	echo "processing dataset: $ds"
-	echo ''
+  # Step 1 - snapshot locally
+  local now=$(date +%s)
+  local snap=${ds}@${snapshot_prefix}${now}
+  echo "creating snapshot locally: ${snap}"
+  if ! sudo /usr/sbin/zfs snapshot "${snapshot_opts[@]}" "${snap}"; then
+    echo "[ERROR] failed to snapshot ${ds}" >&2
+    exit 1
+  fi
 
-	# Step 1 - snapshot locally
-	local now=$(date +%s)
-	local snap=$ds@${snapshot_prefix}${now}
-	echo "creating snapshot locally: $snap"
-	if ! zfs snapshot "${snapshot_opts[@]}" "$snap"; then
-		echo "[ERROR] failed to snapshot $ds" >&2
-		return 1
-	fi
+  # Step 2 - find the latest remote snapshot
+  local rds=$remote_pool/${ds#*/}
+  local inc_snap=
+  local inc_opts=()
+  echo "fetching latest remote snapshot for dataset: ${rds}"
+  local rsnap=$(SSH /usr/sbin/zfs list -H -o name,creation -p -t snapshot -r "${rds}" | \
+        grep "^${rds}@" | \
+        sort -n -k 2 | \
+        tail -1 | \
+        awk '{ print $1 }')
 
-	# Step 2 - find the latest remote snapshot
-	local rds=$remote_dataset/${ds#*/}
-	local inc_snap=
-	local inc_opts=()
-	debug "fetching latest remote snapshot for dataset: $rds"
-	local rsnap=$(SSH zfs list -H -o name,creation -p -t snapshot -r "$rds" | \
-		    grep "^$rds@" | \
-		    sort -n -k 2 | \
-		    tail -1 | \
-		    awk '{ print $1 }')
+  if [[ -n ${rsnap} ]]; then
+    echo "latest remote snapshot: ${rsnap}"
+    inc_snap=${rsnap#*@}
+    # assert that ${inc_snap} exists locally
+    if ! sudo /usr/sbin/zfs list -t snapshot "${ds}@${inc_snap}" &>/dev/null; then
+      echo "[ERROR] could not find ${rsnap} locally (${ds}@${inc_snap} not found)" >&2
+      exit 2
+    fi
+    inc_opts+=(-I "@${inc_snap}")
+  else
+    echo "no snapshot found for ${ds} - doing full send/recv"
+  fi
 
-	if [[ -n $rsnap ]]; then
-		echo "latest remote snapshot: $rsnap"
-		inc_snap=${rsnap#*@}
-		# assert that $inc_snap exists locally
-		if ! zfs list -t snapshot "$ds@$inc_snap" &>/dev/null; then
-			echo "[ERROR] could not find $rsnap locally ($ds@$inc_snap not found)" >&2
-			return 1
-		fi
-		inc_opts+=(-i "@$inc_snap")
-	else
-		echo "no snapshot found for $ds - doing full send/recv"
-	fi
+  # Step 3: send from latest remote to newly created or do a full send
+  if [[ -n ${inc_snap} ]]; then
+    echo "zfs sending (incremental) @${inc_snap} -> ${snap} to ${rds}"
+  else
+    echo "zfs sending ${snap} to ${rds}"
+  fi
+  # Receive options: Always use snapshot as base (remote changes on after
+  # snapshot will cause recieve to fail otherwise); recieving pool receieves
+  # filesystem unmounted to prevent mount collisions.
+  if ! sudo /usr/sbin/zfs send "${send_opts[@]}" "${inc_opts[@]}" "${snap}" | SSH /usr/sbin/zfs recv -Fuv "${rds}"; then
+    echo "[ERROR] failed to send $snap to ${remote_server} ${rds}" >&2
+    exit 3
+  fi
 
-	# Step 3: send from latest remote to newly created
-	# or do a full send
-	if [[ -n $inc_snap ]]; then
-		echo "zfs sending (incremental) @$inc_snap -> $snap to $rds"
-	else
-		echo "zfs sending $snap to $rds"
-	fi
-	if ! zfs send "${send_opts[@]}" "${inc_opts[@]}" "$snap" | SSH zfs recv -Fuv "$rds"; then
-		echo "[ERROR] failed to send $snap to $remote_server $rds" >&2
-		return 1
-	fi
+  # Step 4: After successful sync, trim to he last X snapshots (sync'ed on next run).
+  #         the backup pool will always have X+1 snapshots.
+  if [[ ${snapshot_retention} -gt 0 ]]; then
+    echo "retainng the last ${snapshot_retention} snapshots for ${ds}"
+    # Identify the latest X snapshots for a given dataset (creation, newest to oldest)
+    zfs_latest=`/usr/sbin/zfs list -H -t snapshot -o name -S creation | grep ^${ds}@ | head -${snapshot_retention}`
+    # Identify ALL snapshots for a given dataset (creation, newest to oldest)
+    zfs_delete=`/usr/sbin/zfs list -H -t snapshot -o name -S creation | grep ^${ds}@`
 
-	return 0
+    echo "all snapshots:       $(echo ${zfs_delete[@]})"
+    echo "retained snapshots:  $(echo ${zfs_latest[@]})"
+    # Remove latest snapshots from all set.
+    for keep_snap in ${zfs_latest[@]}; do
+       zfs_delete=( "${zfs_delete[@]/${keep_snap}}" );
+    done
+
+    echo "snapshots to remove: $(echo ${zfs_delete[@]})"
+    # Destroy old snapshots
+    for snap in ${zfs_delete[@]}; do
+      /usr/sbin/zfs destroy ${snap}
+    done
+  else
+    echo "zfs snapshot rentention management disabled"
+  fi
 }
 
 echo "starting on $(date)"
 
 code=0
 for ds in "${datasets[@]}"; do
-	process "$ds" || code=1
-done
-for ds in "${datasets_recursive[@]}"; do
-	process "$ds" recursive || code=1
+  process "${ds}"
 done
 echo
-echo "script ran for ~$((SECONDS / 60)) minutes ($SECONDS seconds)"
-echo
-end "$code"
-echo
-echo '---------------------------------'
-
-exit "$code"
+echo "script ran for ~$((SECONDS / 60)) minutes (${SECONDS} seconds)"
